<a href="https://colab.research.google.com/github/banjuk2/github.io/blob/master/%EA%B8%B0%EC%B4%88%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98%ED%95%99_%ED%85%90%EC%84%9C1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

스칼라

1. 단순한 숫자
2. 방향상 없음
3. 무조건 크기만 있음.
4. 랭크 0인 텐서

In [2]:
#scalar 예시
a=np.array(5)
print('값 = ', a)
print('형태 = ', a.shape)

값 =  5
형태 =  ()


벡터 
1. 숫자들의 배열 
2. 크기와 방향 개념 존재 - 차원 등장 
3. 예시: 속도 
4. 랭크 1 텐서(스칼라보다 한차원 더 고차원)

In [3]:
# 벡터예시 
vec1 = np.array( [5] ) # 벡터는 리스트 형태로 만들어 주어야 함 
print('값 = ', vec1)
print('형태 = ', vec1.shape)

값 =  [5]
형태 =  (1,)


In [4]:
#2차원, 3차원, ....., n차원 
vec2 = np.array( [2,4] ) # 2차원
print('값 = ', vec2)
print('형태 = ', vec2.shape)

vec3 = np.array( [1,2,3] ) # 3차원 
print('값 = ', vec3)
print('형태 = ', vec3.shape)

vec5 = np.array([-1,2,3,4,5])
print('값 = ', vec5)
print('형태 = ', vec5.shape)

값 =  [2 4]
형태 =  (2,)
값 =  [1 2 3]
형태 =  (3,)
값 =  [-1  2  3  4  5]
형태 =  (5,)


행렬 
1. 수의 배열 
2. 벡터와 벡터끼리의 연관성 이해 
3. 선형방정식의 뿌리 ex) 소와 닭은 합해서 8마리, 다리개수는 26개, 소와 닭은 각각 몇마리인가? 
4. 랭크 2 텐서 

In [10]:
# 2X2 정방행렬 
mat1= np.array( [ [1,1], [4,2] ] ) 
print('값 = ', mat1)
print('형태 = ', mat1.shape)

# 4X3 정방행렬 
mat2 = np.array([ [1,2,3], [1,2,3], [1,2,3], [1,2,3] ] ) # 3개의 행렬이 4개가 있다. 
print('값 = ', mat2)
print('형태 = ', mat2.shape)

값 =  [[1 1]
 [4 2]]
형태 =  (2, 2)
값 =  [[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
형태 =  (4, 3)
